apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/s4aicha/S4-projects.git
    path: S4-projects
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: s4aicha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
